### ISSUE TITLE
Modifier manager capabilities deprecating warning

### ISSUE THREAD

**Issue by charlesfries** [ahmadsoe/ember-highcharts#273]
Seeing this deprecation warning in Ember 3.28:

```
DEPRECATION: Versions of modifier manager capabilities prior to 3.22 have been deprecated. You must update to the 3.22 capabilities. [deprecation id: manager-capabilities.modifiers-3-13] See https://deprecations.emberjs.com/v3.x#toc_manager-capabilities-modifiers-3-13 for more details.
```

```
DEBUG: -------------------------------
DEBUG: Ember                 : 3.28.6
DEBUG: Ember Data            : 3.27.1
DEBUG: Ember Model Validator : 3.10.0
DEBUG: Model Fragments       : 5.0.0-beta.2
DEBUG: -------------------------------
```

**Comment by nlfurniss** [comment]
Can you post the full stacktrace?

**Comment by charlesfries** [comment]
```
DEPRECATION: Versions of modifier manager capabilities prior to 3.22 have been deprecated. You must update to the 3.22 capabilities. [deprecation id: manager-capabilities.modifiers-3-13] See https://deprecations.emberjs.com/v3.x#toc_manager-capabilities-modifiers-3-13 for more details.
        at logDeprecationStackTrace (http://localhost:4200/assets/vendor.js:42687:21)
        at HANDLERS.<computed> (http://localhost:4200/assets/vendor.js:42820:9)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:42714:9)
        at HANDLERS.<computed> (http://localhost:4200/assets/vendor.js:42820:9)
        at invoke (http://localhost:4200/assets/vendor.js:42832:9)
        at deprecate (http://localhost:4200/assets/vendor.js:42788:28)
        at modifierCapabilities$1 (http://localhost:4200/assets/vendor.js:17466:62)
        at http://localhost:4200/assets/vendor.js:191767:46
        at CustomModifierManager.getDelegateFor (http://localhost:4200/assets/vendor.js:51041:20)
logDeprecationStackTrace @ deprecate.js:136
HANDLERS.<computed> @ handlers.js:26
raiseOnDeprecation @ deprecate.js:146
HANDLERS.<computed> @ handlers.js:26
invoke @ handlers.js:38
deprecate @ deprecate.js:220
modifierCapabilities$1 @ index.js:8852
(anonymous) @ did-update.js:66
getDelegateFor @ manager.js:714
```

**Comment by nlfurniss** [comment]
@charlesfries should be fixed in [the latest release](https://www.npmjs.com/package/ember-highcharts). Please let me know

**Comment by charlesfries** [comment]
Still seeing it. Not sure why upgrading `@ember/render-modifiers` didn't fix it.

Also I see the deprecation warning appear twice, right as the single `<HighCharts />` component is rendered.

**Comment by charlesfries** [comment]
@nlfurniss Does this addon even need to depend on `ember-modifier` since it doesn't export any modifiers?

**Comment by nlfurniss** [comment]
Yes you're right. However I can't repro. Running `master` and upgrading to ember 4.0.0-beta.8 the only deprecation I see is

```DEPRECATION: Use of `assign` has been deprecated. Please use `Object.assign` or the spread operator instead. [deprecation id: ember-polyfills.deprecate-assign] See https://deprecations.emberjs.com/v4.x/#toc_ember-polyfills-deprecate-assign for more details.```

**Comment by charlesfries** [comment]
Major apologies, after some more looking the issue seems to be caused my dependence on `ember-sortable` and its use of an older version of `@ember/render-modifiers`.  I guess that version discrepancy makes it so that `ember-highcharts` must use that older version in my app even though the newer version is specified. Just having `ember-sortable` installed w/o any of its component/modifer invoked causes the warning.

Thanks for your help and quick responses.

**Comment by nlfurniss** [comment]
> Major apologies, after some more looking the issue seems to be caused my dependence on `ember-sortable` and its use of an older version of `@ember/render-modifiers`. I guess that version discrepancy makes it so that `ember-highcharts` must use that older version in my app even though the newer version is specified. Just having `ember-sortable` installed w/o any of its components/modifers invoked causes the warning.
> 
> Thanks for your help and quick responses.

No worries, thanks for reminding me to do a release. Will follow up with a minor release that removes `ember-modifier`
